### ISSUE TITLE
It seems like something happened with Ygg (again)...

### ISSUE THREAD

**Issue by afronob** [pitzzae/yggtorrent#10]
Everything works fine since your last Cloudflare fix, but now :

That simply test :
```js
const YGG = require('yggtorrent');

var client = new YGG();

client.set_credential('*****', '*******');

//list categories
client.get_categories(function(result) {
        console.log(result);
});
```

```js
/var/www/yggtorrent-pizzae/node_modules/request-promise-core/lib/plumbing.js:130
            throw thrownException;
            ^

TypeError: Cannot read property 'request' of undefined
    at Request.callback [as _rp_callbackOrig] (/var/www/yggtorrent-pizzae/node_modules/yggtorrent/index.js:182:51)
    at Request.plumbing.callback (/var/www/yggtorrent-pizzae/node_modules/request-promise-core/lib/plumbing.js:76:39)
    at Request.RP$callback [as _callback] (/var/www/yggtorrent-pizzae/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/www/yggtorrent-pizzae/node_modules/request/request.js:185:22)
    at onCloudflareResponse (/var/www/yggtorrent-pizzae/node_modules/cloudscraper/index.js:229:12)
    at onRequestResponse (/var/www/yggtorrent-pizzae/node_modules/cloudscraper/index.js:205:5)
    at Request.<anonymous> (/var/www/yggtorrent-pizzae/node_modules/cloudscraper/index.js:149:7)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/yggtorrent-pizzae/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/yggtorrent-pizzae/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.module.exports.loopWhile (/var/www/yggtorrent-pizzae/node_modules/deasync/index.js:70:11)
    at Function.sleep (/var/www/yggtorrent-pizzae/node_modules/deasync/index.js:41:18)
```

**Comment by afronob** [comment]
Nobody has the same error as me ?

`node v8.17.0`
`npm v6.13.4`

**Comment by btpython** [comment]
> Nobody has the same error as me ?
> 
> `node v8.17.0`
> `npm v6.13.4`

I have also this problem you're not alone @afronob

**Comment by fethca** [comment]
The error comes from Cloudscraper which has a Parse Error coming from a regexp match.
 
The last fork of @bestplay9384 solved it during few days, check this thread :  [1020, Access Denied (Custom Firewall Rules) #343](https://github.com/codemanki/cloudscraper/issues/343)

However now it seems to face Captcha error due to change of CloudFlare challenge

**Comment by gtorresani** [comment]
A new version is available, the cloudflare-cookie-scraper part has been outsourced in a docker container
The git repo has been moved
[https://gitlab.onlineterroir.com/yggtorrent/yggtorrent](https://gitlab.onlineterroir.com/yggtorrent/yggtorrent)
An API is also available in a docker container
[https://gitlab.onlineterroir.com/yggtorrent/yggtorrent_api](https://gitlab.onlineterroir.com/yggtorrent/yggtorrent_api)
