### ISSUE TITLE
TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by medinaflav** [pitzzae/yggtorrent#12]
Salut,

Tout marchait bien et d'un coup gros message d'erreur j'ai beau chercher je comprends pas pourquoi..

Avec seulement ce bout de code : 
```javascript
var express = require('express');
var fs = require('fs');
var YGG = require('yggtorrent');

var router = express.Router();
var client = new YGG();
client.set_credential('username', 'password');

router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});

module.exports = router;
```
Je reçois ça :
```
C:\Users\Shadow\myproject\node_modules\request-promise-core\lib\plumbing.js:130
            throw thrownException;
            ^

TypeError: Cannot read property 'request' of undefined
    at Request.callback [as _rp_callbackOrig] (C:\Users\Shadow\myproject\node_modules\yggtorrent\index.js:182:50)
    at Request.plumbing.callback (C:\Users\Shadow\myproject\node_modules\request-promise-core\lib\plumbing.js:76:39)
    at Request.RP$callback [as _callback] (C:\Users\Shadow\myproject\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\Shadow\myproject\node_modules\request\request.js:185:22)
    at onChallenge (C:\Users\Shadow\myproject\node_modules\cloudscraper\index.js:317:12)
    at onCloudflareResponse (C:\Users\Shadow\myproject\node_modules\cloudscraper\index.js:247:12)
    at onRequestResponse (C:\Users\Shadow\myproject\node_modules\cloudscraper\index.js:205:5)
    at Request.<anonymous> (C:\Users\Shadow\myproject\node_modules\cloudscraper\index.js:149:7)
    at Object.onceWrapper (events.js:312:19)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\Shadow\myproject\node_modules\request\request.js:1154:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Users\Shadow\myproject\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.module.exports.loopWhile (C:\Users\Shadow\myproject\node_modules\deasync\index.js:70:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myproject@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myproject@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shadow\AppData\Roaming\npm-cache\_logs\2020-11-14T00_11_18_344Z-debug.log
```
Avez vous déjà eu une erreur de ce genre ?

**Comment by thegostisdead** [comment]
Bonjour, 
Je rencontre également ce problème. 
Avec ce code : 
```javascript
const YGG = require('yggtorrent');

var client = new YGG();

client.set_credential('username', 'mypassword');

// list categories
client.get_categories(function(result) {
    console.log(result);
});
```
Et je reçois : 
```
C:\Users\thego\node_modules\request-promise-core\lib\plumbing.js:130
            throw thrownException;
            ^

TypeError: Cannot read property 'request' of undefined
    at Request.callback [as _rp_callbackOrig] (C:\Users\thego\node_modules\yggtorrent\index.js:182:51)
    at Request.plumbing.callback (C:\Users\thego\node_modules\request-promise-core\lib\plumbing.js:76:39)
    at Request.RP$callback [as _callback] (C:\Users\thego\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\thego\node_modules\request\request.js:185:22)
    at onChallenge (C:\Users\thego\node_modules\cloudscraper\index.js:317:12)
    at onCloudflareResponse (C:\Users\thego\node_modules\cloudscraper\index.js:247:12)
    at onRequestResponse (C:\Users\thego\node_modules\cloudscraper\index.js:205:5)
    at Request.<anonymous> (C:\Users\thego\node_modules\cloudscraper\index.js:149:7)
    at Object.onceWrapper (events.js:422:26)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\thego\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\thego\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
    at Function.module.exports.loopWhile (C:\Users\thego\node_modules\deasync\index.js:70:11)
    at Function.sleep (C:\Users\thego\node_modules\deasync\index.js:41:18)
    at Client.set_credential (C:\Users\thego\node_modules\yggtorrent\index.js:109:35)
    at Object.<anonymous> (C:\Users\thego\Desktop\tmp\test.js:5:8)
```

**Comment by gtorresani** [comment]
Une nouvel version est disponible, la partie cloudflare-cookie-scraper a été externaliser dans un container docker
Le repo git a été déplacer
[https://gitlab.onlineterroir.com/yggtorrent/yggtorrent](https://gitlab.onlineterroir.com/yggtorrent/yggtorrent)
Une api est egalement disponible dans un container docker
[https://gitlab.onlineterroir.com/yggtorrent/yggtorrent_api](https://gitlab.onlineterroir.com/yggtorrent/yggtorrent_api)
