### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by unixfox** [pitzzae/yggtorrent#8]
I tried the library with a basic code:
```js
const YGG = require('yggtorrent');
var client = new YGG();
client.set_credential('username', 'passwd');
```
And I'm getting this error:
```
/var/tmp/yggtorrent/index.js:255
		if (res.statusCode === 301)
		        ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.optionalCallback [as _callback] (/var/tmp/yggtorrent/index.js:255:11)
    at self.callback (/var/tmp/yggtorrent/node_modules/request/request.js:185:22)
    at Request.emit (events.js:305:20)
    at Request.onRequestError (/var/tmp/yggtorrent/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:305:20)
    at TLSSocket.socketCloseListener (_http_client.js:397:11)
    at TLSSocket.emit (events.js:317:22)
    at net.js:667:12
    at TCP.done (_tls_wrap.js:491:7)
    at Function.module.exports.loopWhile (/var/tmp/yggtorrent/node_modules/deasync/index.js:71:23)
```

Also yggtorrent changed their domain to .ws

**Comment by Seebomega** [comment]
Yes looks like they send recaptcha i am trying to find a way but they don t provide any API

**Comment by afronob** [comment]
> Yes looks like they send recaptcha i am trying to find a way but they don t provide any API

Hope that you can found something to do ! Cheers

**Comment by gtorresani** [comment]
A new version is available, the cloudflare-cookie-scraper part has been outsourced in a docker container
The git repo has been moved
[https://gitlab.onlineterroir.com/yggtorrent/yggtorrent](https://gitlab.onlineterroir.com/yggtorrent/yggtorrent)
An API is also available in a docker container
[https://gitlab.onlineterroir.com/yggtorrent/yggtorrent_api](https://gitlab.onlineterroir.com/yggtorrent/yggtorrent_api)
