### ISSUE TITLE
Last Cloudflare patch seems to be missing something...

### ISSUE THREAD

**Issue by afronob** [pitzzae/yggtorrent#9]
With that simply code :

```js
const YGG = require('yggtorrent');

var client = new YGG();

client.set_credential('*****', '******');

//list categories
client.get_categories(function(result) {
	console.log(result);
});
```

At first, Cookies module is missing in dependancies. But you can add it manually.

```js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'cookie'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/yggtorrent_crawler/node_modules/yggtorrent/index.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/yggtorrent_crawler/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Then I got this :

```js
/var/www/yggtorrent_crawler/node_modules/request-promise-core/lib/plumbing.js:130
            throw thrownException;
            ^

TypeError: Cannot read property 'request' of undefined
    at Request.callback [as _rp_callbackOrig] (/var/www/yggtorrent_crawler/node_modules/yggtorrent/index.js:182:51)
    at Request.plumbing.callback (/var/www/yggtorrent_crawler/node_modules/request-promise-core/lib/plumbing.js:76:39)
    at Request.RP$callback [as _callback] (/var/www/yggtorrent_crawler/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/www/yggtorrent_crawler/node_modules/request/request.js:185:22)
    at onCloudflareResponse (/var/www/yggtorrent_crawler/node_modules/cloudscraper/index.js:229:12)
    at onRequestResponse (/var/www/yggtorrent_crawler/node_modules/cloudscraper/index.js:205:5)
    at Request.<anonymous> (/var/www/yggtorrent_crawler/node_modules/cloudscraper/index.js:149:7)
    at Object.onceWrapper (events.js:286:20)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/var/www/yggtorrent_crawler/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (/var/www/yggtorrent_crawler/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.module.exports.loopWhile (/var/www/yggtorrent_crawler/node_modules/deasync/index.js:70:11)
    at Function.sleep (/var/www/yggtorrent_crawler/node_modules/deasync/index.js:41:18)
    at Client.set_credential (/var/www/yggtorrent_crawler/node_modules/yggtorrent/index.js:109:35)
    at Object.<anonymous> (/var/www/yggtorrent_crawler/index.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

Any ideas ?

**Comment by gtorresani** [comment]
[cloudscraper](https://www.npmjs.com/package/cloudscraper) node_module dont work properly with node@10

I have same problem when i run it with node@10.

But if you run it with node@8 the bug is not present.

I have not found any solution to make it work properly with node@10.

**Comment by gtorresani** [comment]
I have deployed a new version with cookie dependency and README.md node8 information

**Comment by afronob** [comment]
Working great with nodejs v8 thanks
